CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -pedantic

all: prime-calculator

prime-calculator: prime-calculator.cpp
	$(CXX) $(CXXFLAGS) -o prime-calculator prime-calculator.cpp

clean:
	rm -f prime-calculator

